---
# Handlers for Cockpit role

- name: restart cockpit
  ansible.builtin.systemd:
    name: cockpit.service
    state: restarted
  become: true

- name: restart cockpit socket
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted
  become: true
