---
# Firewall configuration
firewall_enabled: true
firewall_default_zone: public

# AdGuard Home configuration
adguard_configure_app: true
adguard_firewall_zone: FedoraServer

# DHCP configuration
adguard_dhcp_enabled: true
adguard_dhcp_interface_name: enp6s0
adguard_dhcp_local_domain: lan
adguard_dhcp_gateway_ip: 192.168.10.1
adguard_dhcp_subnet_mask: 255.255.255.0
adguard_dhcp_range_start: 192.168.10.100
adguard_dhcp_range_end: 192.168.10.200
adguard_dhcp_lease_duration: 86400

# FileBrowser configuration
filebrowser_port: 8080
filebrowser_firewall_zone: FedoraServer
filebrowser_root_dir: /srv/filebrowser

# User credentials
adguard_users:
  - name: ndelucca
    password: $2a$10$A/PkUdTvjpRlqwtFvEYEX.L8ypXT3saCpsxE0/XzsUTV6SRZAwJ.a

# DHCP static leases
adguard_dhcp_static_leases:
  - ip: 192.168.10.10
    hostname: ndelucca-server
    mac: "4c:cc:6a:d3:fc:a1"
  - ip: 192.168.10.11
    hostname: ndelucca-raspberry-printer
    mac: "b8:27:eb:f1:af:50"
  - ip: 192.168.10.12
    hostname: ndelucca-raspberry-printer-wireless
    mac: "b8:27:eb:a4:fa:05"
  - ip: 192.168.10.13
    hostname: ndelucca-acer
    mac: "fa:da:6d:73:ff:15"
  - ip: 192.168.10.20
    hostname: ndelucca-tv-tcl
    mac: "48:9e:9d:8f:65:20"
  - ip: 192.168.10.21
    hostname: ndelucca-pixel-8-5ghz
    mac: "1e:9c:15:ee:48:26"
  - ip: 192.168.10.22
    hostname: ndelucca-pixel-8-2.4ghz
    mac: "ca:61:9f:ce:53:ce"

# DNS rewrites
adguard_dns_rewrites:
  - domain: ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: adguard.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: torrent.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: files.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: jellyfin.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: cockpit.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: gallery.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: ndelucca-acer.com
    answer: 192.168.10.13
    enabled: true
  - domain: ndelucca-raspberry-printer.com
    answer: 192.168.10.11
    enabled: true
  - domain: books.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true
  - domain: slicer.ndelucca-server.com
    answer: 192.168.10.10
    enabled: true

# NGINX Reverse Proxy
nginx_firewall_enabled: true
nginx_firewall_zone: FedoraServer
nginx_domain: ndelucca-server.com

# Immich configuration
immich_upload_location: /srv/disks/D-Draco/media/Gallery

# Kavita configuration
kavita_extra_libraries:
  - name: books
    path: /srv/disks/D-Draco/media/Books

# OrcaSlicer configuration
orcaslicer_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32653231303665616139383161393830353334396639633838613533633461353964646132653530
  3262623063643262313966313137343539613665643965340a393665343431383832653036363633
  32346536303335636266663935626565303935346465303336613939303063653437356464393837
  3664666236386631610a383134363334353463393961326163306263366539356363376239313731
  37373131336135326162383931663336303566313561393564326331643533383137
