---
# Variables specific to homeserver group

# Firewall configuration
firewall_enabled: true
firewall_default_zone: public

# SELinux
selinux_state: enforcing
selinux_policy: targeted

# Timezone
timezone: America/Argentina/Buenos_Aires
