---
# Metadata for Cockpit role

galaxy_info:
  author: Your Name
  description: Installs and configures Cockpit web console for Fedora
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Fedora
      versions:
        - 38
        - 39
        - 40
        - 41

  galaxy_tags:
    - cockpit
    - monitoring
    - webui
    - system

dependencies: []
