---
galaxy_info:
  author: Naza
  description: Install and configure OrcaSlicer web-accessible 3D slicer on Fedora
  license: MIT
  min_ansible_version: '2.13'
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []

collections:
  - community.general
  - ansible.posix
