---
# Metadata for Cloud Torrent role

galaxy_info:
  author: Naza
  description: Install and configure Cloud Torrent web-based torrent client
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Fedora
      versions:
        - 38
        - 39
        - 40
        - 41
        - 42
        - 43

  galaxy_tags:
    - torrent
    - bittorrent
    - cloud
    - web
    - downloads
    - media

dependencies: []

collections:
  - ansible.posix
  - community.general
